### ISSUE TITLE
Create Application Statement

### ISSUE THREAD

**Issue by cgefx** [chingu-voyages/v17-toucans-team-01#1]
Create a simple, concise statement of what your application will achieve and the value it has to its users. Every function and feature in the application should reinforce this goal.

**Comment by rnagel3** [comment]
Hi team, looking to add my input. It looks like the point would be to display what our product does. Maybe also have a payment page? I feel that's pretty basic and that would be a good goal to shoot for the MVP.

**Comment by cgefx** [comment]
cool lets just start to list features here, and then we can make a statement from it.  here's a start:

• Buy button that links to Payment Page
• Responsive layout with 3 breakpoints (mobile, tablet, desktop)
• Testimonial section with both click and drag and auto scroll
• Count down timer for sale price
• FAQ section with dropdown answers for each question. 
• Features section with 4X3 icon grid
• Custom colored scroll bar.
