### ISSUE TITLE
Create project mockup/wireframe

### ISSUE THREAD

**Issue by cgefx** [chingu-voyages/v17-toucans-team-01#14]
- [X] Web Layout
- [x] Tablet Layout
- [x] Mobile Layout

**Comment by conor-gaughan** [comment]
We could use something like https://www.figma.com/ - it's a collaborative design tool that doesn't seem to be too intense.

**Comment by cgefx** [comment]
Hi Conor, 

Sorry for the late reply, just getting back into town.  Do you want to try and tackle the mockup?  I have moderate experience with Sketch,  but very little with Figma, so could probably offer some guidance. I think just black and white wireframes for the landing page is all we'd need since the project is a clone.  Let me know your thoughts.
